### ISSUE TITLE
启动hexo 时 ，打开博客出现错误。显示不了

### ISSUE THREAD

**Issue by easyweng** [AlynxZhou/hikaru-theme-aria#1]
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
WARN  No layout: index.html

**Comment by AlynxZhou** [comment]
这个 repo 不是 Hexo 主题， Hikaru 是我自己写的静态站点生成器，Hexo 的主题在另一个仓库里，麻烦仔细看下再发 issue。
