### ISSUE TITLE
更加优雅的评论系统

### ISSUE THREAD

**Issue by DaPaoStudio** [AlynxZhou/hikaru-theme-aria#2]
要不要考虑整合一下Valine - 一款快速、简洁且高效的无后端评论系统。
[https://valine.js.org/](url=valine.js.org)

**Comment by AlynxZhou** [comment]
首先你走错了，这个和那个 Hexo 主题不是一个仓库，我自己的网站用的不是 Hexo，我自己写了个生成器，所以大概这个仓库就我一个人用，很显然我自己并不需要 Valine……我觉得把评论放在 GitHub issue 很符合我的受众。

然后 Hexo 主题的话……之前有人提过 LiveRe 还是 Valine 来着……应该是没问题的，但是我懒，我最近刚考完试，可能等我过两天回家闲着的时候考虑弄一下吧或者如果有人愿意提 PR 的话。
